### ISSUE TITLE
Log courier locks files on windows

### ISSUE THREAD

**Issue by scratch-net** [driskell/log-courier#119]
I have some logs which rotate hourly and after some time (not instantly) I get
2015/02/21 06:07:26.318553 Error prospecting d:\logz\log.6.txt: GetFileAttributesEx d:\logz\log.6.txt: Access is denied.

(6 is the last log, they are in total 0-6)
After I close the courier, file #6 gets deleted.
I use version from stable branch

**Comment by driskell** [comment]
I think this is expected and not a problem. The file isn't actually locked, it's deleted. If the file was locked the rotations would never have been allowed, and the app probably wouldn't have been able to write at all.

Try changing `"dead time"` config on the file input to less than one hour - say, 30 minutes. This will close the file after 30 mins no change.

There's no reliable way to detect if a file has been deleted on Windows while we have it open, and the delete gets "deferred" until we close the file, so it's simply a case of getting the dead time right. I might explain it more in the docs. Be good if you can try this and confirm though.

For the curious technical folk - the underlying kernel space error on the get attribute call isn't actually access denied, it's "STARUS_FILE_DELETED". But there is no corresponding user space error so it maps to the nearest: "ERROR_ACCESS_DENIED". See https://support.microsoft.com/kb/113996

**Comment by scratch-net** [comment]
But it stops sending logs to logstash, so "dead time" seems to be a required option. I will set it and let you know how it goes

**Comment by scratch-net** [comment]
I mean why not close file if we receive any error? We're unable to use it anyway

**Comment by driskell** [comment]
No error is received when reading the file.
The error in your OP is when looking for new files, and there's no way to tell that the 6 file seen is the same one we are reading - it could have been renamed etc. and we can't access the unique file ids to check this because of the error.

I am not entirely sure why it would stop shipping. My guess though is the app stops writing when it tries to rotate beyond 6, because of the same error (pending delete / access denied). The dead time change should solve this as it'll rid the error. I'll improve docs as mentioned.

There's no real way for me to fix this perfectly that I can find, without writing windows drivers to read the log files... Sorry I can't offer a perfect fix, I'd like to if I could! If any Windows developer gurus find anything I'm all open ears though.

**Comment by driskell** [comment]
In 2.0 I'll be decreasing the dead time default btw as I'm now confident the entire pipeline is perfectly capable of reopening files reliably if they change again. It'll likely be down to 30 minutes or less. This would resolve the problem for all but the fastest rotating logs (within 30min rotation).

FYI the problem is Windows specific too - other platforms have no problem due to how they handle file deletions.

**Comment by scratch-net** [comment]
Ok, I'm just trying to figure out how it's happening. Please correct me if I'm wrong:
1) There are 8 files opened for reading (Current + 0..6)
2) In an hour rotation happens, Number 6 gets deleted by my app.
3) As it is opened for reading it becomes a "Zombie" which is not detectable untill we try to do something with it, thus preventing an app from functioning properly (unable to rotate).
4) At some point Courier starts to output messages like " Error prospecting file number 6" every 5 seconds or so.

So, Courier does know that something is wrong with file #6(it outputs it's path). Maybe not immediately but it does! And I see no technical problem to stop flooding the console and do the proper error handling (close file handles or even restart the whole thing or whatever needed to resume proper functioning).

The problem with "dead time" is the race condition that will definitely occur at some point regardless of its value. I just don't see any reasons to wait for "dead time" if we already have the error with the file name and able to resolve it.

**Comment by driskell** [comment]
OK so here's what I think is happening, assuming you're paths is "log*.txt"

1) 8 file opened for reading, log.txt and log.0.txt through to log.6.txt
2) After an hour, log.6.txt is deleted - however, we have open handle, so it is marked pending deletion, subsequently rotation fails (it cannot rename log.5.txt to log.6.txt - as 6 is still there pending deletion)
3) This is where app logging stops as it likely tried to create new log.txt but failed (as it couldn't rename existing one)
4) Log Courier then prospects for new files matching the "log*.txt" filter.
5) Log Courier checks each file it found, when it checks log.6.txt it fails to access it because it is marked pending deletion - access denied is reported
6) Log Courier reports the same error every 5 seconds **this is a bug - it should report once - I'll investigate this one**

Now, we cannot know to close log.6.txt. What if the file was renamed from c:\logs\log.6.txt to c:\temp\log.6.txt? A new file was then created at c:\logs\log.6.txt but we no longer have access (inherited permissions turned off yesterday or something.)

Without being able to read the file attributes of this problematic log.6.txt (which we can't if pending deletion and we can't if we don't have access) - we cannot compare unique file ID (which is unchanging, even if file moved) and so cannot know which/what file this is - new? renamed?. The only way to know it was renamed is if we monitor c:\temp\log*.txt and we see the log.6.txt appear there with the same file ID. There's also no way for Log Courier to know the filename of a file it has open because it can change at any moment if it's renamed. It only knows the filename when it was opened - internally, even if log.txt is renamed to log.0.txt, it'll still think it's log.txt. It relies on the prospector to track renames and notice the change by comparing unique file ID. If the movement is to a folder outside of the monitor paths though - it does not notice - and we can't be monitoring entire disk. So we end up with a log.6.txt that we have no idea what it refers to: new or renamed.

There's also some AV and such that when scanning the file lock it - so you can get momentary access denied error. In this case we do not want to close the file - the error will clear up momentarily on the next prospector scan.

I can see your argument, that the evidence available would suggest that it is most likely that log.6.txt can be closed, and that it is highly likely it is in fact one of the files we're reading from, and almost certain that it is Log Courier preventing the deletion from happening immediately. However, it would be wrong to write code that makes such assumptions, no matter how likely. Inevitably it will break as it will behave wrongly, and the question would be - how do we stop it behaving wrongly? The fix would be to remove the assumption. So we'd end up with a "dead time" option anyway.

I think the best solution here is that, tweaking dead time. In an ideal world though, the app should also handle rotation error by simply continuing to log to the current file - it seems the app here stops logging if rotation fails - if it continued writing you'd have less of an issue; rotation would fail for about 12-16 hours but then it would succeed. Not as expected, but working none-the-less and not losing logs.

I'll investigate the repeating error - that's definitely not supposed to happen! :+1:

**Comment by driskell** [comment]
Apologies for the long post too. I tried to explain the situation as best I could and as less-technical as I could!

**Comment by scratch-net** [comment]
Thanks for your explanation, much clearer to me now. I'll check with Nlog on how to handle such situations. Maybe (maybe)there could be some configurable "assumptions" about how to behave when this happens. I'm not also sure about how dead time is calculated but if it started from the moment of renaming then race conditions could be avoided.

Thanks for the gread job and keep it up )

**Comment by driskell** [comment]
I've located the repeating error and will merge that fix soon once I can test it.

Regarding NLog. Looking at the code if any error occurs during file rotation it will fail to log and discard the logs it would have written. On the next attempt to log same will happen. So it will do as you experienced and stop logging until the rotation is successful. May be worth raising an issue with them. A good reproduction step could be to create a log.6.txt with no permissions to the logging application.

**Comment by scratch-net** [comment]
Nlog has the fallback ability. It seems to be working, however needs more testing

**Comment by driskell** [comment]
Ok no problem. Feel free to drop any notes in here for other users if you have a moment!

Will merge the fix with the #122 fix in next few days. Thanks for reporting!
