### ISSUE TITLE
.deb packages

### ISSUE THREAD

**Issue by zabbal** [driskell/log-courier#127]
Would be handy to see .deb creation support included into repo. Ideally the packages should be of high quality (see lintian for tests) so they could be included directly into Ubuntu and Debian repositories to facilitate maintainability and deployment. The inclusion into official repo might take some time though so in the meantime something like ppa (for ubuntu) would be perfect for testing.

**Comment by driskell** [comment]
I have already begun the process for RPM, following Fedora guidelines closely, and have setup a COPR repository which will be documented soon.

For DEB it's a learning curve for me and I will inevitably have some Fedora bias as CentOS is my home. I'm definitely wanting to do this though - and help with links to guides or detailed annotated PRs would be hugely appreciated to ease the learning!

**Comment by jmreicha** [comment]
+1

would something like fpm be viable for building a dev or rpm similar to the logstash-forwarder project does it?

**Comment by driskell** [comment]
fpm is feasible and I welcome others to use it as they need for their own custom deployments.

For myself, I know RPM well enough to produce a spec and SRPM pretty quickly with mock. This I upload to COPR which uses mock too. Mock allows for reliable CLEAN builds - that is, each package (source and binary) is built in a minimal chroot'ed system so dependency lists are guaranteed to be correct and there's no dependency issues. It also guarantees my package is built against latest dependency packages for each platform without need for many different VM (CentOS/RedHat/Fedora/5/6/7)

I plan to learn DEB if I can (and welcome guidance from others) and do the same, using mock to ensure clean builds.

I just not sure how fpm would fit for me - I'd end up using mock anyway but although it supports SRPM out of the box it doesn't FPM.

I kind of see FPM as an internal tool for specific deployments, rather than for public repositories. I'm still open to it though if there becomes a benefit but not seeing it much at moment - RedHat/CentOS is covered and it's just DEB really where there's a technical gap

**Comment by rabidscorpio** [comment]
+1 for this, although I probably don't have the guidance you're looking for

**Comment by mcnewton** [comment]
I've built .deb packages for log-courier as it's easier to push around to many different systems. There's an issue in that the required version of go isn't available in Debian, but otherwise works fine. Will check the state of it and see if I can easily do a pull request.

**Comment by driskell** [comment]
@mcnewton That's interesting. What version of Go is available? Is it the same for Debian and Ubuntu or would Ubuntu have newer?

**Comment by driskell** [comment]
Wow. Debian stable is 1.0?! Hmmm. Testing has 1.3 I guess that building for Debian will need the golang-go package from testing. Fortunately once built it isn't needed so the resulting package will be installable fine on a stable distribution. Might be something to add into README.

Ubuntu wise, trusty onwards has 1.2 at least so that's good there. For lucid/precise (and any older) I guess it will need it from testing if it's there.

**Comment by mcnewton** [comment]
Yes, it's only building it that has the problem; fine once built. I'll try and sort it out when I'm back in work tomorrow.

I may be able to test on a jessie system to see if it builds OK without hacks there - will see. Don't have easy access to any Ubuntu systems to test with at the moment so will depend on whether I have time to install one to try with.

**Comment by mcnewton** [comment]
I've done a pull request for the debian packaging. The only thing that will need to be updated is the debian/changelog file - a new stanza at the top for each new version that is released.

Haven't been able to test on jessie yet, but added a build dependency for golang-go, so hopefully it should "just work". Wheezy continues to require go installed separately as noted in debian/README.

The gem packaging may work... I've just updated it slightly to try and auto-detect version numbered files, but haven't tested yet. It worked OK until now when the versions were hardcoded into postinst/prerm, but that doesn't feel right for a released version. Not sure if there is a tidier way to do that generally.

It's set to build as a debian native package, so it won't be acceptable to debian as-is. But at least it's a start, and should hopefully be useful for those wanting to install a package to keep things clean.

**Comment by driskell** [comment]
Thanks @mcnewton really appreciate the leg up here.

I'll do some playing around and testing and look at a third party repository on PPA for Ubuntu.

Regarding gem I think best to drop it for purposes of merge as I would prefer to concentrate on 1.5 Logstash plugin system.

Again, many thanks.

**Comment by mcnewton** [comment]
I've dropped the gem packaging and re-pushed to the PR. Another option might be to build the gem and install it as part of the log-courier package, then it's up to the admin to manually install it if they need to.

I'm not sure on the best way to handle this in Debian - mature "sub-packages" (such as perl modules, for example) are build as separate debian packages and in the repositories. That usually seems like the cleanest way and easiest for the admin; to use the o/s packaging to manage everything. But some people like it differently. Logstash is fairly new here so I guess there isn't really any precedence in how plugins are handled at the moment, so maybe best as you say to leave it up to the sysadmin. Especially if logstash will be getting some plugin system soon anyway.

I usually feel that systems are "dirty" when they've had things installed on them from other packaging systems, though!

But agree it's tidier at the moment to remove it.

Cheers,
Matthew

**Comment by mcnewton** [comment]
Oh, also on a comment further back, note that jessie (testing) should become stable in a few weeks anyway, so the "go version problem" will hopefully "go" away, too. Standard debian always-up-to-date-with-the-latest-from-5-years-ago problem. :-)

**Comment by driskell** [comment]
Hehe. At least you know that Debian has had at least 5 years of strenuous testing.

Agree on the packaging aspect - though I believe the mature sub-packages aspect in your example is usually due to them providing more complex python applications (Munin comes to mind, so does SaltStack) that have dependency on those python modules but are too complex to be installed via pip/easy_install, so they package those as dependencies. In my CentOS experience (I have little experience in Debian but hope it is similar!) they package the modules in such a way that "pip" and "easy_install" still work etc, so it's a bit of a side-by-side mesh.

So in the Logstash scenario there's not really any reason to make them a package. And in the end I think it would need Logstash themselves, when packaging Logstash in .deb, to ensure it was done in such a way to allow it. For example Logstash self-contains all of its gem dependencies, so that would mean Logstash would need to stop doing that and instead depend on system gem packages (so our plugin packages can also depend on those system gem packages.) This would be major I think having looked at how the plugin system is built. And to be fair, the current system is cross-platform. To use distribution packaging means different system per platform.

But regardless! Nothing to stop Log Courier itself being packaged :+1: and I'll get started making that a reality soon. Thanks!

**Comment by gfa** [comment]
i may help to get log-courier into debian, after jessie is released. ubuntu could sync from debian
it should get into next release whatever it is released. 
do you plan to support more time any particular release? because after debian gets freezed no updates to packages can be made, i can provide updated releases on testing/sid but once it gets freeze, i have to support the same version until the release gets EOL (about 3.5 years)

i'm talking about log-courier client side, i can't help with gem for the server side, i know nothing about ruby packaging

**Comment by driskell** [comment]
I wouldn't be able to afford any time to maintain two version side by side. I think the best thing is to avoid the vendor repositories entirely. Ubuntu has PPAs (https://launchpad.net/ubuntu/+ppas) and that would be a perfect fit, allowing me to control the updates and available support etc. Not sure if Debian has something similar but it looks like PPA can be used on Debian too (or at least, people elude to it in my Google search!)

**Comment by mcnewton** [comment]
Software creators/maintainers don't generally also maintain the official Debian package, unless they are Debian developers as well. So you wouldn't be expected to maintain the official Debian package. What does happen, of course, is that the Debian version gets gradually more and more out of date, which sometimes means people go to the main software project asking for help for ancient versions. What they should really do is either complain to the Debian maintainer (who can't do anything due to Debian policy), or install the version from the project. But having it in Debian directly does make is a shedload easier for people to install.

Providing your own separate repository is pretty simple for Debian (and Ubuntu), but of course you should try and do a good job at making sure it actually works on current Debian releases. But then the same could be said of having a debian/ directory in the project anyway.

Some projects will just build the .deb and leave it to people to install. This can be fine, but I think it happens more in the RPM world. It's really not hard for people to grab the source and build the Debian package for themselves.

So, there are a few options. But worrying about getting it into the main Debian repository and having to maintain that shouldn't be one of them! :)

**Comment by gfa** [comment]
when i said support older version i refer to security bugs or data loss, i don't expect you to maintain and ancient version.  

nowadays with backports people using stable can enjoy recent versions easily

**Comment by hvisage** [comment]
Willing to help test .deb packages, especially on some older Ubuntu (typically LTS) and Debian systems (7.x)
