### ISSUE TITLE
Windows build information

### ISSUE THREAD

**Issue by huksley** [driskell/log-courier#150]
Hello! I`ve just build from source on Windows.
The information stated on home page is incomplete. Here is what I found out:

Requirements:

Windows 8.1 OK
The golang compiler tools (1.4.2 works ok)
git (TortoiseGit works ok - must be installed with command line tools) 
mingw msys (bash, gcc, make etc all the defaults)

On Windows: 
Launch MSYS command prompt, type: cd c:/ and navigate to folder with log-courier. Execute make. bin/log-courier.exe will be produced. Execute in in standalone cmd.exe prompt to check it is working ok.

**Comment by mmlumba** [comment]
Is Windows 7 ok for this build?

**Comment by driskell** [comment]
#145 reports problems with building on Windows due to requirement for "ln" command and a bash-like shell (so cmd.exe does not work). Using mingw msys seems it will get around this problem.

Really only make should be needed so it's simpler. I'll be working on this as part of #145.

Thanks for the information though - I might refer to mingw msys too if updating docs.
