### ISSUE TITLE
Proposal: Protocol Spec, Users

### ISSUE THREAD

**Issue by sorenvind** [driskell/log-courier#157]
Log-Courier seems very cool!

However, it would be nice if the Docs included a little more info about a few things (i.e. it would greatly help selling this solution to colleagues and/or frenemies):
- A protocol spec, or at least the promises made by the protocol (rather than "the Log-Courier protocolis improved over logstash-forwarder"). E.g. what happens if log-courier is killed and restarted, what happens if the receiver fails?
- Is the system running in production anywhere? Large deployments?

I am currently considering it against rsyslog, and this would greatly help the decision.

**Comment by driskell** [comment]
Yes the README is due to be touched up a little. I thought I had the guarantees in there but guess not! Sorry about that.

A core Log Courier goal is to guarantee at-least-once delivery of ALL events to Logstash.
On startup it resumes files from their last guaranteed position. This position is only updated once the Logstash plugin has responded to acknowledge it has received the event.

However, if a Logstash crash happens, events will be lost. Logstash itself offers no guarantees. However, this is on the Logstash roadmap and it will soon have persistent queues (guaranteed but slower), and eventually full end-to-end acknowledgement (fast) - the moment it has either of these, I will be working to update the Log Courier plugins to take advantage of them.

So the only time you can lose events is due to a Logstash server problem - issues on senders and the network don't matter anymore. This drastically reduces surface area for problems so even though there's no end-to-end guarantee just yet it's nearly there.

I run this in production with around 50-60 servers (mostly small loads with about 5 very high loads), with some across the internet using TLS with client certificate verification. I've also helped fix various issues for others using Log Courier in production. "Large" is subjective, but from perspective I do remember there was one where I almost wet myself when I was told my tool was being used on over a hundred servers with what I remember as a very large event throughput (can't remember specifics.) Others might laugh at that amount though :+1: :-)

**Comment by driskell** [comment]
FYI. I created Log Courier because of my high loads and needed reliable data. I was getting lots of i/o timeouts with Forwarder and seeing large amounts of duplicates logs that had I not investigated would have probably have gone unnoticed. I also have several servers with unique file rotation algorithms that actually seem to break Forwarder, making it reingest the entire file on rotation. Also I had some QA/Dev systems that during startup would reingest files randomly.

These issues were all fixed in Log Courier and are the two main differences listed in the README:

* The publisher protocol is rewritten to avoid many causes of "i/o timeout" which would result in duplicate events sent to Logstash
* The prospector and registrar are heavily revamped to handle log rotations and movements far more reliably, and to report errors cleanly

**Comment by sorenvind** [comment]
Wonderful response time! This is already very helpful.

I am currently considering a scenario with hundreds of servers from around the world throwing logs at a central ELK stack, possibly using intermediate proxies in each DC for additional reliability. It needs to just work. Do you feel that log-courier would be ready for such an environment?

By the way, the setup with local proxies requires us to run logstash on those machines (writing to disk) in addition to log-courier pushing files on from the disk-written files. Do you have comments on the setup, besides the obvious need for a log-courier-server component to handle the setup in the proxies? :)
