### ISSUE TITLE
Support for Redhat 5.x

### ISSUE THREAD

**Issue by mmlumba** [driskell/log-courier#159]
Hello,

I would like to try log-courier on an RHEL 5.x server but I could not find an EPEL for it. Will there be support for this in the future, or should I find another type of logstash forwarder for RHEL 5.x?

Thanks

**Comment by driskell** [comment]
No problem!

Just bear in mind that Go itself does not officially support RHEL5, I think due to the age of the kernel and compiler tools. Though from my own experience it works perfectly fine on 64-bit RHEL5. I have noticed on some (not all) 32-bit RHEL5 systems though that sys logging was broken (it would log with dates decades in the past) but seemed otherwise fine!
