### ISSUE TITLE
bring back random server selection on failure

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#161]
Hi,

A "re-open" of https://github.com/driskell/log-courier/issues/82

Could we please get the random server selection on _failure_ aswell as on initial connection? At least as an option which would enable this.
Unfortunately the current option which chooses the next server in list just makes too much trouble.
Example: 4 LS servers, 2000 clients. Initially they get randomized on connect, so every server has ~500 clients connected. But then, after a logstash config update, we have to restart the LS cluster. This ends up with all / most of the clients going to one server (i.e. LS1). Eventually, the server crashes due to the load and all clients connect to the next one - LS2. Same thing happens with it, and it goes on and on.

If we could have the option to randomize the servers during failures, the load would spread out to multiple LS servers rather than the one which gets online faster.

**Comment by driskell** [comment]
Hi

I'll get this in for 1.7 as an option. Sorry about the problems!

2.0 atm will connect to all servers specified at the same time and either use instant failover (with fail back as soon as the original 'preferred' server is available) or load balancing. I'll work in some option for making it behave the same at the moment - though the 2.0 input plugin should cope with many clients easily as it's a single IO thread and a single input thread, rather than a thread per connection.

**Comment by driskell** [comment]
@sysmonk Are you OK to test the change I pushed?

It will "shuffle" the server list on startup randomly. Then it will failover through that list. Once it gets to the end it will shuffle the server list again and start again. So every server should have a completely randomised list and failover randomly - but you also have the guarantee it won't try the same server twice.

I'd also like your thoughts on load balancing (which I'm working on for 2.0). If Log Courier could connect to multiple servers simultaneously and balance across them would that be useful? I know you've used the zmq transport options previously and I'm curious on how you yourself had envisioned it working.

**Comment by sysmonk** [comment]
Thanks! I'll test out the change some time this/early next week.

```but you also have the guarantee it won't try the same server twice.``` except when last element of oldList is the same as first element of newList :) but that's ok

Re the 2.0 - how would the balancing work ? Would it send each payload to a new server? 
What about if a server is slow(-er) than others?

Best case scenario would be if it connected to all servers, and would have stats on the last X payloads sent to each server, and would try sending more events to the faster / less overloaded servers, but still sometimes send events to the slower ones to see when they get less overloaded. Might be more complex though :) Does that make sense?

**Comment by driskell** [comment]
Yes I did spot that scenario :) It will move on after one reconnect though so I feel sufficient - I can prevent it later on with a tweak - just drop the current server from list before shuffling, and throw current server to the end.

Currently 2.0 will balance them with "least-outstanding" - faster servers will receive more payloads since their queues will flush faster. Unlike the ZMQ system though, actual network failures or crashes are noticed and recovered quickly rather than waiting for a timeout. However, when a server freezes so you get timeouts there will still be an issue potentially, until it times out it may block if the maxpending payload count is reached.

The plan is to implement some exponential backoff so multiple timeouts (from a frozen server) should reduce impact over time until it's say, retry every 30 minutes or something (configurable).

If it's OK I'll close this off as the randomness is in master and is working from my own tests. Feel free to reopen if not.
