### ISSUE TITLE
Heka vs log-courier

### ISSUE THREAD

**Issue by stephanbuys** [driskell/log-courier#166]
Hi all, this is probably not a this vs that question as the title implies, just wanted to know if you've looked at Heka and how you consider it compares to log-courier? Both written in Go, etc...

We're looking for a log shipper to "get behind" and have been looking at log-courier as a very strong candidate.

**Comment by driskell** [comment]
Never knew that existed! Looked interesting.

I suppose the main difference from my perspective (as maintainer) is project goals. Log Courier is pure shipper. It's intended to get logs off a host quickly and send to a remote server for centralised processing in a way that is resistant to network failures.

I've only skimmed the summary for Heka but it appears to me to be a processor like Logstash (though looks not as flexible) which does a lot more than Log Courier.

Generally, I expect Log Courier to be small with limited processing power (filter and multiline only) - just so you can concentrate on processing in a dedicated location rather than tampering with configs across a data centre.

**Comment by driskell** [comment]
Maybe one day there'll be a Heka input for Log Courier :)

**Comment by stephanbuys** [comment]
@driskell thanks for the prompt reply, I went to ES training a couple of weeks ago and it seems the logstash roadmap doesn't include a definite future for lsf, so I've been looking for non-ruby alternatives. But I like your clarification, makes it a bit easier to map the space.
