### ISSUE TITLE
Ability to exclude file formats from harvesting

### ISSUE THREAD

**Issue by madhusudan-d** [driskell/log-courier#167]
log-courier shipping all files in configured directory along with .gz(zipped files).
Is there any way with which we can tell log-courier not to include specific file formats??. There is exclude option in logstash for doing this. do we have any similar configuration in log-courier??. 
I am using ELK stack and I can see some garbage data from .gz (zipped) files.

Thanks in advance.

**Comment by driskell** [comment]
What is your "paths" set to?

If you include .gz files it will try to ingest them. There is usually no need for exclude in this case as you can just include "access-*.log" for example in order to not include the gz files.

Also, in nearly all cases you need only follow the current file, so can just specify "access.log" - it will follow rotations as necessary.

**Comment by madhusudand** [comment]
The path is set to /service-abc/* . and srervice-abc have many log files which are of different formats. we have few of .log and few of _log.

**Comment by driskell** [comment]
You can specify multiple paths as such:

```
"paths": [ "/service-abc/*.log", "/service-abc/*_log" ]
```

Would that work?

**Comment by driskell** [comment]
I will consider adding an "exclude_paths" option onto the roadmap for version 2. For now though hopefully the above will help?

**Comment by madhusudand** [comment]
sure.. Thanks....

**Comment by driskell** [comment]
Not had any other request for this and not needed it myself so will close this, but happy to receive PRs.
