### ISSUE TITLE
Where to find packaged application for direct use

### ISSUE THREAD

**Issue by ashwgupt** [driskell/log-courier#180]
@driskell though the log-courier looks quite a promising proposition but I am still struggling to figure out the simple steps on how to install to use it. 

It's neither going to be straight forward for me to build it in our restricted environment nor I want to get into this. Builiding a code come with many other side issues of dependencies resolutions. I am very keen to get a packaged executable for RHEL and other platform like how Logstash-forwarder comes handy.

Would you or anyone mind sharing the location if one exists?

**Comment by driskell** [comment]
RPM information is in the README:
https://github.com/driskell/log-courier#public-repositories

All dependencies are Go, and Log Courier is Go, and so there are no dependency issues. The built binary is self-contained and will run on any 'like' system.

**Comment by ashwgupt** [comment]
Thanks @driskell 

I shall try it out while I am still trying to figure out issue with my logstash-forwarder ssl handshake.

Can you also suggest, where to find the client side config file details?

**Comment by driskell** [comment]
What do you mean client side config file details?
Do you mean Log Courier config? You can just drop in a logstash forwarder config - it's the same format and supports pretty much all the same options, but more.

If you read the README there's a set of links to the various documentation at the bottom, including configuration. The configuration documentation also includes a list of examples.
https://github.com/driskell/log-courier/blob/master/README.md#documentation

With regards to having to install a plugin to work with Logstash - this is for two reasons:
1. The lumberjack plugin bundled with Logstash was previously unmaintained and had many issues (time outs, no client cert auth, broken tag shipping, utf8 issues, no logging of when clients fail, single threaded handshake, etc.).
A rewrite was necessary to fix them and so the courier plugin was born.
2. Better control of the logstash side code was desired to further allow Log Courier to develop into a reliable shipper.

Hope this helps! As for the SSL certificate issue you'll likely hit same issue in Log Courier and if you raise issue I'll try to help best I can. Both projects share a lot of code! :-)

**Comment by ashwgupt** [comment]
I am even fine to do without SSL at this stage of setup. As logstash-forwarder seems much tricky to use let me get started with the courier to get my speed up.

May get back to you if any help required for using or building the package.

**Comment by ashwgupt** [comment]
The url you mentioned above about the RPM - https://github.com/driskell/log-courier#public-repositories takes me to the repo file content, isn't their a ready built binary?

Do I have to install 'only' to use the log-courier, and can't use like an executable the way one can use Logstash-forwarder?

Also, to install Courier at Logstash server level, would I need any Root right?

**Comment by driskell** [comment]
> The url you mentioned above about the RPM - https://github.com/driskell/log-courier#public-repositories takes me to the repo file content, isn't their a ready built binary?

Setting up `yum` makes things easy and means you can update the package easily. It also takes care of the single zeromq dependency the RPM has at the moment (soon to be removed) by pulling it from EPEL.
(I said earlier all dependencies were Go but forgot about zeromq... sorry)

If you just require the RPM, just browse the repository URL: https://copr-be.cloud.fedoraproject.org/results/driskell/log-courier/ but you will need to source the zeromq dependency from EPEL: http://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/zeromq3.html

I can see there may be demand for just RPM without any ZeroMQ. I'll think about that.

> Do I have to install 'only' to use the log-courier, and can't use like an executable the way one can use Logstash-forwarder?

As far as I know, logstash-forwarder doesn't provide just an executable. Do you mean just a RPM file and manually install with `rpm` rather than `yum`? See above.

> Also, to install Courier at Logstash server level, would I need any Root right?

No. Just be logged in as the Logstash user, and use the plugin manager to install the plugin. This is by far the easiest part I think.

**Comment by driskell** [comment]
I guess my definition of simple is different. `yum` method is simple I thought. If you need an `rpm` method for whatever reason I can see the difference, and forwarder does provide `rpm` but does not provide `yum`.

**Comment by ashwgupt** [comment]
Yeah, forwarder provides the RPM, which makes it's adoption fast and easier. I was expecting something similar from Courier but if not possible, I will try out building.

Can you please comment on the error I got for plugin installation at Logstash server side? Do I need to get the plugin file before doing the actual install?

**Comment by driskell** [comment]
I appreciate that regarding standalone RPM - I had not previously. I'll think of a better plan for 2.0.

> Can you please comment on the error I got for plugin installation at Logstash server side? Do I need to get the plugin file before doing the actual install?

Can you try using Logstash 1.5 GA? You appear to be running RC4.
You shouldn't need anything. Logstash will connect to rubygems.org and download everything it needs automatically. Maybe you are running through a proxy though and it's not able to download?

**Comment by driskell** [comment]
@ashwgupt Regarding plugin installation - I've raised PR with Logstash as it doesn't actually report network error - it just states the plugin does not exist. So make sure you have internet connection - as it needs to connect to rubygems.org in order to download the plugin and dependencies.

I'm going to work on more documentation improvements shortly and provide direct links to RPM and DEB etc. that can be used rather than the repositories, and also link to the GitHub ZIP/TARGZ downloads.

**Comment by ashwgupt** [comment]
Seems like the issue...just found that the network access is not present (and not allowed either) from the server. So in such cases, is there 'any' other way to get the Courier plugin into Logstash?

I guess, this also been made available in ready-made way, would have helped people on-board fast.

**Comment by ashwgupt** [comment]
I guess https://github.com/driskell/log-courier/blob/master/docs/LogstashIntegration.md#manual-installation is the answer, let me try it out.

**Comment by driskell** [comment]
Will close this as old.

I've not found much time to work on a full build script to attach things to GitHub but might look at it in the future.
