### ISSUE TITLE
log-courier plugin no longer works with logstash 1.4.x (error since milestone removal)

### ISSUE THREAD

**Issue by dbeckham** [driskell/log-courier#181]
The log-courier Logstash plugin no longer works with Logstash 1.4.x. Logstash startup fails with the following error: 

>The error reported is:
>courier must set a milestone. For more information about plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones

It appears that b54acb87844dcdb4a276e3e494f0ea9d70c0345b from #164 was when milestone support was removed.

**Comment by driskell** [comment]
@dbeckham Thanks! Yes this backwards compatibility was overlooked.

Are you able to upgrade to Logstash 1.5?

It may be complex to try support both versions with different plugin systems - in which case you could try downloading 1.6 and installing that instead.

**Comment by driskell** [comment]
I will examine this in detail to see if its possible to support both.

**Comment by driskell** [comment]
Using `LOGSTASH_VERSION` from `logstash/version` may make this possible.

https://github.com/elastic/logstash/blob/master/lib/logstash/version.rb

**Comment by dbeckham** [comment]
@driskell sorry for the late reply.  We will be upgrading to Logstash 1.5, but not for a few weeks or so. For now, I'm just sticking with the 1.2 version we've been using.

**Comment by dbeckham** [comment]
@driskell we use elastic's puppet module for logstash and as it turns out, they have no immediate plans on supporting Logstash 1.5 until they get done with all ES puppet work for the ES module's 1.0 release.  So, I'm faced with rofldeploying Logstash 1.5, or sticking it out until they are done. Can you help me understand what changes I need to make to the log-courier code in order to work under 1.4? I have a feeling your recent changes may help overcome a lot of the brokenness in Logstash 1.4

**Comment by driskell** [comment]
Compatibility was broken in https://github.com/driskell/log-courier/commit/b54acb87844dcdb4a276e3e494f0ea9d70c0345b#diff-ffe2f55456b8ab5913639b0fd3e64297
The problem was 1.5 actually states `The plugin is not maintained because it has milestone` or something!

Basically you just add the `milestone` line back into `lib/logstash/inputs/courier.rb` and `lib/logstash/outputs/courier.rb`

I'll commit soon to make it backwards compatible by adding a check in the code for version 1.4 and only adding milestone then.
