### ISSUE TITLE
debian init script returns 0 in case of failure

### ISSUE THREAD

**Issue by p53** [driskell/log-courier#189]
Hi,
i found that debian init script returns 0 even in case it fails to start, i see that there is:

do_start() {
  start-stop-daemon --start --chuid log-courier --quiet --pidfile $PIDFILE --exec /bin/sh --test > /dev/null || return 1

and then later in startup/stop functions:

case "$?" in
      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;

so that's why it returns bad return code

**Comment by driskell** [comment]
Thanks. I know there is some work to be done to normalise the init scripts.

One thing to bear in mind though - it will probably always return 0 anyway (in the near-future), as Log Courier will generally always successfully "start" - but may fail immediately after it started (due to configuration error etc.) because Log Courier itself is not "daemon-aware" and neither is Golang. There are ways to make it aware but too complex outweighs the benefit.

**Comment by p53** [comment]
maybe it would be useful to add config test before starting, at least something to prevent false positive
