### ISSUE TITLE
Logstash not starting due to Courier Input - "can't convert nil into string"

### ISSUE THREAD

**Issue by ninjada** [driskell/log-courier#197]
upgrading my logstash 1.4.x environment with log-courier to 1.5.1 

fresh installed and ran:
```
/opt/logstash/bin/plugin update
/opt/logstash/bin/plugin install logstash-input-log-courier
```

seeing logstash crash with the following error with my pre-existing input config:

error:

```
{:timestamp=>"2015-06-30T16:51:41.835000+1000", :message=>"The error reported is: \n  can't convert nil into String", "plugin"=>"input/courier", "port"=>5000}
```

input.conf

```
input {
  courier {
    port => "5000"
    ssl_certificate => "/etc/pki/tls/certs/ssl.crt"
    ssl_key => "/etc/pki/tls/private/ssl.key"
    transport => "tls"
  }
}
```

any ideas?

**Comment by driskell** [comment]
Please remove `logstash-input-log-courier` and install `logstash-input-courier`. Config doesn't need changing.
The old name is not used anymore and will be deleted soon.

As for the error I think it is error from another plugin. The fact the message says plugin courier was a bug - it was getting attached to all messages even those not from the plugin (sorry). I believe fixed in newer version but you must install under the new name.

**Comment by ninjada** [comment]
did the trick, cheers @driskell
