### ISSUE TITLE
Add option to send the TimeZone to logstash

### ISSUE THREAD

**Issue by dkirrane** [driskell/log-courier#203]
I want log-courier to ship the TimeZone of it's server to the LogStash server

I'd like to then pass this TimeZone field to the date filter on the logstash side e.g

```
    date {
        match => [ "log_timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]
        locale => "en"
        timezone => "%{timezone_passed_by_log_courier}"
    }
```

In my case the `log_timestamp` field above is made up of entries in the log statement but is missing the TimeZone.
`add_field => [ "log_timestamp", "%{year}-%{month}-%{day} %{time},%{ms}" ]`

Maybe TimeZone can be an extra field attached to the event prior to shipping

**Comment by driskell** [comment]
My method on one of my logs is to specify it as a hard coded field in the config file though I can see if you have global servers that's not at all ideal. The preferable fix is for the logging application to correctly log in a non-local time dependant way (most apps do) but again not always easy to modify an app.

It's definitely worth considering since we already send the hostname log path and offset etc.
