### ISSUE TITLE
COPR unreliable as a repo

### ISSUE THREAD

**Issue by blakeblackshear** [driskell/log-courier#205]
Would it be possible to put the rpm packages somewhere other than copr? This is the second time in recent history that it has been down for maintenance for an extended period of time.

**Comment by driskell** [comment]
I don't know where else to put them.

A related issue would be whether the new location provides a build environment or whether it would mean I have to host and maintain my own. The advantage of COPR is I can upload the RPM SPEC file and the associated code ZIP file and it will build the source packages and binary packages for me on RedHat 6 and 7 on multiple architectures.

I've looked at places like [Bintray](https://bintray.com) but they don't provide the build environment, and I don't believe I would have sufficient time to maintain such an environment myself in order to provide reliable and efficient packaging.

**Comment by driskell** [comment]
If you have some suggestions they're all welcome - and if anyone did wish to take over / help out with the packaging aspect that would be great too :+1:
