### ISSUE TITLE
Non-fatal POSTUN scriptlet failure in rpm package log-courier

### ISSUE THREAD

**Issue by martinhynar** [driskell/log-courier#228]
Hi,

I wonder why log-courier is restarted in %postun? If log-courier is not running, you get the warning message 'Non-fatal POSTUN scriptlet failure in rpm package log-courier'. Also, I would not expect log-courier to be started, because it might be not configured at that point.

I have this scenario:
VM image with preinstalled log-courier is started (at the moment log-courier 1.7.3)
For certain packages, yum update is fired to make them up-to-date (this is easier way to have them updated than creating new VM image too frequently).

**Comment by driskell** [comment]
Can you confirm when you updated, that log-courier was not configured? That might explain the problem. I do know there was this happening with previous packages and the package was fixed (but when installed fixed package it would still throw the error because it runs this script from the old package.)

Will fix up the scripts for next version to ensure it only restarts if it was already running.

**Comment by martinhynar** [comment]
log-courier 1.7.3 was only installed, never configured and never started. Then update to version 1.8.1 was triggered with the warning appearing.
