### ISSUE TITLE
JSON encoding issue via Apache JSON

### ISSUE THREAD

**Issue by srizzling** [driskell/log-courier#238]
As Apache tries to convert the JSON it uses "readable" chars it confirms to using "/x" control sequence for characters, which aren't accepted by the JSON spec.

So what I get is errors like: 
https://github.com/logstash-plugins/logstash-codec-json/issues/2

":exception=>#<LogStash::Json::ParserError: Unrecognized character escape 'x' (code 120)"

I know its possibly not the fault of log-courier but could there be way to preprocess, and fix control sequences like this? 

For example: here is one of the sequences that fails
\\xc3\\xa

I feel as to this is stopping log-courier push ANY logs as it fails to push this log, or is my investigation failed there too?

Thanks,
Sriram

**Comment by srizzling** [comment]
@driskell Do you think it might be possible to add a new codec called mutate, so then I can modify it before its before pushed to logstash?

**Comment by driskell** [comment]
If you could outline requirements I can examine the possibility. Generally though I see Courier as a direct to Logstash rather than Elasticsearch, so anything Logstash does already I'm less inclined to implement unless there is benefit. There's also the maintainable aspect so anything hugely complex probably best as a Logstash plugin :-)

Filter - this benefits because it reduces data transmission for noisy log files

Multiline - this benefits because using Multiline codec at Logstash side is unsupported still (it has weird side effects I couldn't fix) and when using the Multiline filter at Logstash side it removes the ability to use multiple filterworkers (`-w n`)

**Comment by driskell** [comment]
For this Apache JSON I think I would use mutate and then JSON filter. Does that work?

**Comment by srizzling** [comment]
Ok, yes that did work and the errors don't appear on logstash side,  BUT I'm still getting issues with log-courier not sending the messages.

I feel as though log-courier has filled up its own publishing queue as you can see from lc-admin utility:

Publisher:
  Status: Connected
  Speed (Lps): 84.35
  Published lines: 381
  Pending Payloads: 5
  Timeouts: 0
  Retransmissions: 0

Logstash logs shows me no errors.

and Log-courier logs seem to be fine as well.

Is there anything else that I can look into to diagnose the problem?

**Comment by driskell** [comment]
Pending Payloads is how many data "chunks" have been sent to Logstash, but not yet received acknowledgements for. This generally means the Logstash pipeline has stalled.

Most common reason is memory problems in Logstash which break the pipeline, or crashing filter works. If you've modified filters recently that's likely the cause. Sometimes the errors don't appear in the log file due to buffering though. If you run Logstash manually from command line you might see them if you can reproduce it when running it like that.

Other option is to `kill -QUIT pid_of_java` and it'll send a thread stack trace to the Logstash log file (or wherever `stdout` is going from Logstash). This you can examine and look for `|filterworker` threads, if there aren't any, your filters have crashed.

**Comment by srizzling** [comment]
https://gist.github.com/srizzling/791f25b08dfc14b86170

I don't seem to have any filter threads working. Its funny how it stops only certain machines from pushing logs.

**Comment by driskell** [comment]
Sorry I meant `|worker`!

It's difficult to see what's happening in that trace since there is a worker thread. However, the courier input is blocked trying to push into the filters, and the output is blocked trying to pull from the filters. So the worker isn't working properly for whatever reason it seems. What's the JSON filter configuration?

**Comment by driskell** [comment]
Will close. Can open if anyone still has similar issues. Though the final issues in this topic likely unrelated to the OT
