### ISSUE TITLE
Load-balancing Logstash

### ISSUE THREAD

**Issue by jacobweber** [driskell/log-courier#241]
I'm using log-courier and logstash, and I'd like to prepare for a high volume of logs. I'd also like to have more than one logstash instance in case one goes down.

Do you recommend using ZeroMQ? I see that you're phasing it out with version 2.0, but is it still the best option for 1.x? It looks like other message queues aren't supported.

**Comment by driskell** [comment]
ZeroMQ will load balance well, but it does not cope with failures well. It's not a "reliable" transport and keeps trying to send events to the dead node for a while until it fills its buffer and overflows. Because Log Courier needs acknowledgements before it can continue, this eventually stalls until those events timeout and get resent to another server, which starts things going again, but then it'll stall again until a timeout. It'll repeat this cycle until the ZeroMQ buffer fills, then it'll be fine. But once the failed server resumes, ZeroMQ will flush that buffer and you'll get duplicate events.

If that's acceptable, then you can use it. But the removal is for the above reasons - so much in ZeroMQ is transparent and not controllable by Log Courier. I did manage to make it work at one point but I'd actually made ZeroMQ redundant at that point and all it was doing was making connection management a nightmare. So the next version of Log Courier would just go back to TLS over TCP and manage load balancing itself.

Also, note that filebeat is on the verge of release and may have some load balancing available due to how it uses libbeat. Though I don't know yet if it'll be reliable "at least once" or how well it will work.

**Comment by jacobweber** [comment]
Thanks for the info. Sounds like there's not a perfect solution right now. I may try to get by with a single logstash instance for the time being, and wait for LC2 or filebeat.

**Comment by DanKans** [comment]
@driskell  What about using software/hardware load balancers and add it into "network" -> "server" section in log-courier configuration file (as a regular logstash node)? Did you noticed any issues in case of reconnecting and etc.? 
Thanks in advance!

**Comment by driskell** [comment]
Load balancing will work much better now in master branch. It'll connect to all servers if `method` is set to `loadbalance`. I need to push some more enhancements before release though but generally was working well when I used it and testing is welcome.

**Comment by driskell** [comment]
Will close as it now in 2.0 in master branch. Will enhance it over time
