### ISSUE TITLE
Question: removal of zeromq

### ISSUE THREAD

**Issue by martinhynar** [driskell/log-courier#250]
Hi!

I've seen you are planning to remove zmq from log-courier in 2.0 version. This became quite a hot topic for me as Salt introduced recently dependency on zmq4 from own repo which collides with EPEL. (see https://github.com/saltstack/salt/issues/28474) Having log-courier without zmq would be great news for me. Do you have some date in mind when this could become true (fingers crossed)?

**Comment by sysmonk** [comment]
I'm also waiting for the 2.0 release with the new mechanism that will replace ZMQ! Also interested in when it's gonna happen!

**Comment by driskell** [comment]
Looks like SaltStack will be fixing it soon!

Regarding 2.0 I've picked up work on it again. I've been restructuring the repositories to split the Ruby library and Logstash plugins away from Log Courier itself so it's easier for me to release independently, and also simplifies testing etc. I've been mostly concentrating on a new plugin architecture to improve Logstash stability memory-wise, but I'm returning to Log Courier now since the 2.0 things that are in place (simple load balancing and failover, multiple codecs) are more useful.

The load balancing is working but just needs a bit of maturing so it can cope better when one of the hosts fails.

I'm planning to push what I have, whatever state it is in, very soon, so people can build, test, even contribute. It'll be the 2.0 branch but merged with latest changes and with the repository cleaned up removing the Ruby library and plugins. If need be I can maintain the 1.x branch separately.
