### ISSUE TITLE
Updating Log-courier to work with Logstash 2.0

### ISSUE THREAD

**Issue by kmroz0991** [driskell/log-courier#256]
I saw that you released an update for -v 1.8.2 but it doesn't seem to be updated in your yum repo. Is this going to happen soon?
Thanks,

**Comment by driskell** [comment]
1.8.2 was a plugin update only. For Logstash 2.0 compatibility just update the plugin and it will update to 1.9.0 which is compatible.

Latest Log Courier binary is 1.8.1 and works fine.

It is confusing as far as I'm concerned as there's multiple different components and I have been using just a single version number. I'm in the process of splitting the repository into four components with each their own version which will make it less confusing and also mean I can release quicker updates on each component. That's why the new plugin versions (1.8.3-1.9.0) don't appear in current change log.

Latest versions are roughly:
Log Courier 1.8.1
Ruby Courier Library (used by plugins) 1.9.0
Logstash Input Plugin 1.9.0
Logstash Output Plugin 1.9.0
