### ISSUE TITLE
Connection failed to initialise :error=>"Socket closed"

### ISSUE THREAD

**Issue by dhavalb-ezdi** [driskell/log-courier#258]
Trying to get log-courier working on AWS. Here is my setup... (OS: 14.04.2 LTS, Trusty Tahr   x64)
Server 1
dpkg -l | grep logstash
ii  logstash                             1:2.0.0-1                           all          An extensible logging pipeline

Configuration: (/etc/logstash/conf.d/logstash.conf)

input {
  courier {
    port => 5514
    ssl_certificate => "/opt/logcerty.crt"
    ssl_key => "/opt/logcerty.key"
  }
}
output{
 sqs {
  queue => "aws_q_name"
  access_key_id => "XXXXXXXXXXXXXXXXXXXX"
  secret_access_key => "xxxxxxxxxxxxxxxxxxxxxxxxxx"
 }
}

Server 2:

dpkg -l | grep logstash
ii  logstash                             1:2.0.0-1                           all          An extensible logging pipeline

Configuration: (/etc/logstash/conf.d/logstash.conf)

input {
sqs {
  queue => "aws_q_name"
  access_key_id => "XXXXXXXXXXXXXXXXXXXXXXX"
  secret_access_key => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
}
filter {
  grok {
...
filters
....
}
if "_grokparsefailure" in [tags] { drop {} }
}
output{
 stdout{}
 elasticsearch {
 hosts => "hostname:80"
 ssl => false
 flush_size => 5000
 }
}

Server 1 is behind ELB. Log-courier client is connecting to DNS name of ELB. Port are open in security group of ELB and Instance as well. I am able to see logs on Kibana of AWS Elasticsearch Service.

Issue is, i am receiving warning logs on Server 1 very frequently.

{:timestamp=>"2015-11-19T09:11:58.575000+0000", :message=>"Connection failed to initialise", :error=>"Socket closed", :peer=>"IP1:13631", :level=>:warn}
{:timestamp=>"2015-11-19T09:11:58.818000+0000", :message=>"Connection failed to initialise", :error=>"Socket closed", :peer=>"IP2:38890", :level=>:warn}
{:timestamp=>"2015-11-19T09:12:28.575000+0000", :message=>"Connection failed to initialise", :error=>"Socket closed", :peer=>"IP1:13649", :level=>:warn}
{:timestamp=>"2015-11-19T09:12:28.819000+0000", :message=>"Connection failed to initialise", :error=>"Socket closed", :peer=>"IP2:38902", :level=>:warn}

Also not able to see logs on client side for log-courier. Is location is different from /var/log/.. ?
Is there any issue in configuration? or bug?

**Comment by driskell** [comment]
Log Courier logs are in /var/log/messages or /var/log/syslog
Is the ELB running in TCP mode? What configuration?
Also what is the configuration of Log Courier?

**Comment by dhavalb-ezdi** [comment]
Yes, ELB is running on TCP with SSL mode. ELB is configured with certificate. Back-end authentication is not configured on ELB. 

Log Courier configuration ...
# cat /etc/log-courier/log-courier.conf
{
        "network": {
                "servers": [ "logstash.host.com:5514" ],
                "ssl certificate": "/opt/logstash-forwarder.crt",
                "ssl key": "/opt/logstash-forwarder.key",
                "ssl ca": "/opt/logstash-forwarder-ca.crt",
                "timeout": 15

        },
        "files": [
                {
                        "paths": [ "/home/ubuntu/app-logs/*/*/app.log" ]
                }
        ]
}

I installed log-courier on 15-20 hosts. No logs found for log-courier in /var/log/syslog in none of them. I tailed logs with last 2000 lines and grep "log" but no logs found for log-courier. 

Please let me know if any more information needed. Thanks.

**Comment by driskell** [comment]
You need to run ELB in TCP mode only. What is happening is the ELB is removing the SSL layer and attempting to pass the protocol to Logstash directly unencrypted. Logstash is then expecting an SSL layer negotiation, and because it isn't happening, sees it as a corrupt connection and closes it with failed to initialise.

Try running ELB in TCP mode.

Just be aware that connections are persistent. Once Log Courier is connected it stays connected. So you'll find it difficult to achieve even balance. For example if one instance fails, and all connections reconnect through to another instance. Once the original instance comes back online there'll be no connections coming in. I believe ELB has a max connection time which eventually closes the connection which might help, but it does interrupt connectivity and could duplicate logs if Log Courier is prevented from receiving an event acknowledgement.

**Comment by driskell** [comment]
Will close this as it's been some time and I believe we found the correct solution.
