### ISSUE TITLE
Is there a way to tell log-courier to follow filepath instead of file inode number?

### ISSUE THREAD

**Issue by aashishmodak** [driskell/log-courier#260]
Hello,
I have a production server that is periodically doing rsync of logs to central server. And i have installed log-courier on central server to push logs to logstash.
When rsync happens on the existing file, the inode changes and log-courier takes this as a new file and send it all-over again to logstash.
Is there way to tell log-courier to follow filepath instead of file inode number?

Similar requirement was on log-stash-file-input plugin.
https://github.com/jordansissel/ruby-filewatch/pull/34

**Comment by driskell** [comment]
Following only the file path would likely not fix anything as if the replacement file contains new events it would need to be closed and reopened so that Log Courier opens the new file (rather than keeping the previous deleted file open). So it's not a simple logic, and in a way we are telling Log Courier to open new files at the offset of the last file, which wouldn't make sense. It would likely mean if your source log rotates it would be broken too.

Some solutions I can propose:
1. Use the rsync flag that updates files in place. My guess is rsync creates a new file and renamed it into place.
2. Only rsync log rotations such that the behaviour is then expected (files are always new)
3. Rsyslog the events centrally if you can (this is probably the best way IMHO) such that you stream events to log files in the way Log Courier expects.

**Comment by aashishmodak** [comment]
Thanks for your proposal. 
I am testing out rsync in-place update flags. 
You may close this issue.
