### ISSUE TITLE
Skipping Events in Logcourier in Linux

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#282]
Posting this query as per the redirection request 
https://github.com/elastic/logstash/issues/4734#issuecomment-190283508
#4734

I have deployed 3 logstash configuration files in my server which is processing 3 different kinds of log files(.xml,.log and .txt). I am using 3 logurier files(version 1.6) to fetch the log files and logstash(version 1.5.4) to process the log files. Daily I am getting tons of log files, log courier fetching all the log files from the location but my logstash skips many events.

I am running the setup in my redhat linux 3.10.0-229.e17.x86_64 version and JDK 1.7. Am I missing any thing to sort out this issue.

**My logstash file:**

```
input {
   courier {
        port => xxxx
        transport => "tcp"

    }
}
filter{
.....
}
output{
elasticsearch {       
          index => "logstash-server1-%{+YYYY.MM.dd}"
          host => "XXXXXX"
                cluster => "server_cluster" 
                protocol => "http"
                document_id => "%{fingerprint}"               
        }
}
```

**Logcourier File:**

```
{
    "general": {
        "log level" : "debug",
        "persist directory" : "<.logcourier file location>"     
    },
    "network": {
        "servers": [ "127.0.0.1:xxxx" ],        
        "transport": "tcp"
    },

"files": [
        {
            "paths":[
                    "/Mylogdata/error/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/vg67-*.xml"

                    ],
            "fields": { "type": "sss_log" },
            "codec": {
                "name": "multiline",
                "pattern":"<regular expression>",
                "negate": true,
                "what": "next"
            },
            "dead time": "1s",

        }
    ]
}
```
Do I need to add any additional property to overcome this issue.. I am using the same configuration for all the 3 configuration files(Logstash and Logcourier).

In have used debug mode below is the recorded information which I have found in the log file. 
`2016/02/29 06:52:09.632178 Skipping file (older than dead time of 3s): /fgh/temp/root.xml`

**Comment by driskell** [comment]
Do you know where the missing lines are from?
Does that "Skipping file" appear during startup or is it appearing periodically whilst running?
Is there a reason for such a small dead time configuration?

**Comment by driskell** [comment]
It's good to also check the Logstash log file since sometimes elasticsearch output can hiccup and lose events. Only reason I can think Log Courier would be losing some is if the dead time is so low it's causing it to think new files don't need reading since by the time it sees it the dead time has passed, but I've never known this to happen since there's code to prevent this happening.

**Comment by Rajeshkumar123** [comment]
@driskell 
1. Do you know where the missing lines are from?
Exactly I am not aware of this.

2.Does that "Skipping file" appear during startup or is it appearing periodically whilst running?
Its not appearing at startup. File skipping is happening randomly somewhere in middle of the process.

3. Is there a reason for such a small dead time configuration?
Yes. I am getting tons of files daily so I don't want my logcourier to spend much time in a single log file. Inorder to speedup the process I have reduced the deadtime. Please suggest me the right configuration If I am wrong.

**Comment by driskell** [comment]
If you can work out what lines are missing that will be great. My guess is that where a file is skipped due to dead time it's those lines that are missing, and none other.

Can you try a dead time of 30 seconds? Prospector scans every 10 seconds so a file can reach dead time before it is noticed. There is a check for this that SHOULD work but we should rule it out. If you can put dead time of 30 seconds it means on each scan it shouldn't miss it.

Also - can you let me know how the files are populated and rotated? Is it you have lots of small files, and they receive a single write and a new file is made for next write, or is it that files receive many writes like a traditional log file? Can you also confirm that the last line of each file that is shipped does indeed appear in ES (to rule out it being last line that is missing.) Also a fuller log file spanning a period of time from Log Courier in a gist would be great.

I would advise upgrading to 1.8 too as it fixes issues with closing files too quickly when dead time is low.

**Comment by Rajeshkumar123** [comment]
I have increased my deadtime to 30s now it looks somewhat better since I have doing lot of elasticsearch correlation it seems to be slow than previous run but it avoids skipping of file to a greater extent.
1. can you let me know how the files are populated and rotated?
I have two kinds of log files. New log files will be generated whenever an application runs another type is new information will be get appended on the log file and once the file size exceeds it will create an another file.

2. Is it you have lots of small files, and they receive a single write and a new file is made for next write, or is it that files receive many writes like a traditional log file?
I have lots of small files which receives single write and I also have many writes which writes like a traditional log . I am processing both kinds of logs.

Currently I have updated my version to 1.8 and monitoring my process with that. Will update you if that resolves my issue. Can I use deadtime of 5s in my new version?

**Comment by Rajeshkumar123** [comment]
For me `1.6` working fine when I have increased the dead time to 20s. The updated version of `1.8` also working fine based on the dead time. Now I am facing one new issue. The thing is logcourier picking up the existing logs available in the log directory without any problem. At the same time when a new log fall in to the location, logcourier reads the log file but its not sending the event to Logstash. I have validated this with the help of `.logcourier file` generated and I can see the entry of newly fallen log file in it. 

If I have deleted my `.logcourier' file and if I restared my logcourier process it picking up entire log file.

I don't know why it was happening.

**P.S**: My logcourier configuration is same as which I have posted it here before. I just changed only the deadtime.

**Comment by driskell** [comment]
> At the same time when a new log fall in to the location, logcourier reads the log file but its not sending the event to Logstash. I have validated this with the help of .logcourier file generated and I can see the entry of newly fallen log file in it.

What do you see in the .log-courier for this file? Can you enable admin in Log Courier and provide the output of "lc-admin" status command? See: https://github.com/driskell/log-courier/blob/1.x/docs/AdministrationUtility.md

**Comment by driskell** [comment]
>  At the same time when a new log fall in to the location, logcourier reads the log file but its not sending the event to Logstash

> "/Mylogdata/error/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/vg67-*.xml"

I wonder if this is related to either the XML file or Multiline. Possibly, the file is discovered, opened, and read from, but it never generates an "event" because either:

1. The file does not have a new line at the end - so it looks like an "unfinished" line
2. Or the multiline processing is not finished

If you can get the `admin enabled` setup and use `lc-admin` there is status information for the multiline processor as well as the line reader so we'll be able to see what is happening. If you can provide example file contents and the regular expression for multiline too that will help examine that. If you can `hexdump -C file.xml` one of the files that is not getting events sent through you can easily check (1) - just check the file ends with an "0A". If not, then the file isn't actually finishing it's line at the end, so Log Courier stands waiting for it to be finished.

**Comment by Rajeshkumar123** [comment]
I have used the lc-admin to monitor the status information of newly fallen log file in the directory . I have got the below information.
```
"State: /../vg67.xml (0xc2132c70e0)":
  Status: Dead
Prospector:
  Watched files: 6066
  Active states: 6066
Publisher:
  Status: Connected
  Speed (Lps): 0.00
  Published lines: 0
  Pending Payloads: 0
  Timeouts: 0
  Retransmissions: 0
```
I have checked the file using the command suggested by you `hexdump -C file.xml`. I couldn't see "0A" anywhere instead of that I saw "\n" at the end of file. Let me know if you need any further details.

**Comment by Rajeshkumar123** [comment]
If there is any issue in XML or Multiline means it shouldnot pick and send the events to logstash for existing logs in the directory right?.
I am facing the above issue for newly falling log files especially .xml type of files only.

**Comment by Rajeshkumar123** [comment]
I have analyzed the logcourier 1.8 functionality for newly falling XML log files. It fetching only certain files and it skipping rest of the files.
Is this anything related to java version . My current java version is `1.7.0_75`. My dead time is `30s`. Please find the .logcourier information recorded,

```
2016/03/16 05:53:40.053367 Registrar received a new file event for /../vg90.xml
2016/03/16 05:53:50.090168 Skipping file (older than dead time of 30s): /../vg90.xml
```

The above message is keep on recording in repeat mode.

**Comment by driskell** [comment]
Java can only cause problems at the Logstash side. Log Courier is native not Java so that's all fine.

Can you put in the gist any log messages you see BETWEEN those two? And some context from before and after? In isolation it's difficult to see. Even if you can get a full few hours worth into a gist it'll help.

**Comment by driskell** [comment]
Any chance to look further into this?

**Comment by Rajeshkumar123** [comment]
I couldn't see any specific details in the log messages. I can see only the above log messages getting recorded in repeat mode. Its never happening for rest of the log files. I am facing this only in XML type of log files.

**Comment by driskell** [comment]
Maybe I will be able to. If you could post more context from the logs from before and after those two lines that'll help. Even a days worth in a gist.

**Comment by driskell** [comment]
If you can get more context that will be great. I need to see some more logs to work out what is happening here.

**Comment by driskell** [comment]
I'll close this - but if you do want to keep looking into and can provide more log context (a day worth or so in a gist) let me know and we can reopen.
