### ISSUE TITLE
 log-courier 2.x: Multiline codec: Multiple patterns definitions not working 

### ISSUE THREAD

**Issue by jfrome** [driskell/log-courier#297]
When using the following configuration, no data is sent to logstash:
```
"codecs": [
    {
        "name": "multiline",
        "max multiline bytes": 10485760,
        "patterns": [
            "!^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}",
            "!^(|@)[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{4}"
        ],
        "what": "previous"
    }
],
```
Individually both patterns work, but when configured together, no output is the result.

**Comment by driskell** [comment]
As long as lines match any pattern they are buffered.
In your configuration whatever matches the second pattern would actually match the first and vice versa.
I think due to the negate.

Thinking of ways to do this I wonder if a full negate is required so you can say buffer lines that don't match any pattern. Maybe there's a need for negate in pattern AND overall!

**Comment by driskell** [comment]
I've thrown in a new `match` parameter which defaults to `any`. If you set this to `all` it'll require that all patterns match. In your case, it'll require that all patterns don't match (since you negated them) and then you'll get your desired behaviour.

Your scenario is a common one (I have a huge amount of Log Courier 1.8 with ugly big patterns which I added multiple patterns to solve, but I would've hit your same issue on some of them!)

**Comment by jfrome** [comment]
Thanks!  In initial testing it appears to be working as designed.
