### ISSUE TITLE
Testing flag: push data from offset 0

### ISSUE THREAD

**Issue by atmosx** [driskell/log-courier#306]
Hello,

I'm using `log-courier` in testing environment and the way it works by gives me troubles, I have to come up with nasty workarounds.

When `log-courier` starts, reads the file and keeps track of the offset. The data that resides in the log file is not getting pushed to `logstash`. I need to pipe new data to the log file and sometimes even piping the same kind of data won't work - can't tell why atm.

I would love to have a flag used in the testing environment where `log-courier` would read, filter a file and dump the data directly to logstash.

Comments, thoughts and workarounds are welcomed.

**Comment by driskell** [comment]
Have you tried deleting the file that keeps track of offsets, `.log-courier`, which would sit in the current directory, and then restarting `log-courier` with the `-from-beginning=true` flag?

This removes all file history from `log-courier`, and tells it to start all unknown files it meets during initial startup from the beginning, rather than resuming from the end. It'll then process all new data from that point onwards too.

If you have issues where data should be getting shipped but isn't, `lc-admin` is a good tool to work out where that data is and why it isn't shipping. If you have logs I'm happy to explore them with you.

**Comment by atmosx** [comment]
I'm starting log-courier in a new container and mount log volumes. I will try to work with the `-from-beginning=true` thanks!

**Comment by driskell** [comment]
Thanks. Note that `-from-beggining` only works if there isn't a `.log-courier` file, as it tells it where to start on files since there's no previous state.
