### ISSUE TITLE
Configuration error: /admin/listen address must be specified if /admin/enabled is true

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#307]
When admin.enabled is true, it requires the listen address to be set. The documentation https://github.com/driskell/log-courier/blob/master/docs/Configuration.md#listen-address though, says:

```String. Optional. Default: tcp:127.0.0.1:1234```

So it should default to tcp:127.0.0.1:1234, rather than be a required field.

Log Courier version 2.0.0

**Comment by sysmonk** [comment]
Also, kinda related - if this is not a documentation bug and it really should default to tcp:127.0.0.1:1234, then it would be nice if it defaults to the same value for lc-admin, so that you can run ```lc-admin reload``` without the need of specifying the -config or -connect...

**Comment by driskell** [comment]
Thanks! Are you using RPM/DEB per-chance?
I built in per-package defaults for each platform that are "embedded", such as config path, so that `lc-admin` can, for the most part, run without needing any parameters. (Though it didn't quite work for 2.0.0 and I just fixed it yesterday - I just wanted to get things released and not hold it longer.)

Might be related to the embedding of the configs, that's all!

**Comment by driskell** [comment]
Sorry, butter fingers ! :)

**Comment by sysmonk** [comment]
No, i've built it from source, default branch a few hours ago.

**Comment by driskell** [comment]
Ah OK. I'll get it fixed!

I notice I didn't update Building From Source docs either :\
But if you `export LC_DEFAULT_CONFIGURATION_FILE=/etc/log-courier/log-courier.yaml` for example before running the `go generate` and `go install` it'll embed that as a default configuration path. That'll allow you to run `log-courier` without a `-config` option. And once 2.0.1 is out you'll be able to run `lc-admin` and it'll read in the listen address from the config.
