### ISSUE TITLE
just a question: AverageLatency time unit?

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#310]
Hi,

What is the averageLatency time in? I've got kinda huge values, like 735426.185386 856725.107616

The requests were finished in less than a second, so i'd assume miliseconds - but then agin the numbers would also be too big... Microseconds? Nanoseconds?

**Comment by driskell** [comment]
It's in nanoseconds. It measures the time *per-event*, so for large payloads it divides by number of events and will generally be smaller, where for smaller payloads it will be larger just due to overheads. During testing it does seem to work well though especially over time as it's takes a running average of the changing values.

It uses it to help queue things. When logs are trickling through it makes no difference. But when you have super large spikes it balances them really well for me.

**Comment by driskell** [comment]
I'll close this as answered.
