### ISSUE TITLE
go get stuck at go-logging.v1

### ISSUE THREAD

**Issue by littlesnitch** [driskell/log-courier#317]
Hi all,

I have the problem, that get get is no being finished.
Problem is, that with proxy after export http_proxy and https_proxy I execute
go get -d github.com/driskell/log-courier
gets stuck. If enabling verbose with
go get -v -d github.com/driskell/log-courier
I get the following
github.com/driskell/log-courier (download)
Fetching https://gopkg.in/op/go-logging.v1?go-get=1
Parsing meta tags from https://gopkg.in/op/go-logging.v1?go-get=1 (status code 200)
get "gopkg.in/op/go-logging.v1": found meta tag main.metaImport{Prefix:"gopkg.in/op/go-logging.v1", VCS:"git", RepoRoot:"https://gopkg.in/op/go-logging.v1"} at https://gopkg.in/op/go-logging.v1?go-get=1
gopkg.in/op/go-logging.v1 (download)

Could you please help here?

Thank you in advance.

**Comment by driskell** [comment]
Hi

This is due to an old git version that does not support redirects. The way gopkg.in works is that it redirects to the relevant version of go-logging (in our case version 1.) But if Git is not new enough it causes Git to hang.

Are you trying to build version 1.8.3? Version 2.0.3 wouldn't have this problem as I vendored in the dependencies so you could upgrade. If you're not ready then you'll just need to clone down the go-logging repository yourself I'm afraid. In the "workspace" where you have `src/github.com/driskell/log-courier` you need to create `src/gopkg.in/op` and clone the v1 branch (important) of https://github.com/op/go-logging into that folder as `go-logging.v1`

**Comment by littlesnitch** [comment]
That's the try to compile logcourier 2.0.3
Installed is go version:
go version go1.5.1 linux/amd64
unter CentOS 6.7

**Comment by littlesnitch** [comment]
Ok, after fetching
https://github.com/op/go-logging/tree/v1
https://github.com/go-yaml/yaml/tree/v2
https://github.com/tylerb/graceful/tree/v1
and unpacking to directories
src/gopkg.in/op/go-logging.v1
src/gopkg.in/yaml.v2
src/gopkg.in/tylerb/graceful.v1
everything worked smooth.
I have now a running logcourier, thank you.

**Comment by littlesnitch** [comment]
Golang 1.5 is for CentOS6 last available package from EPEL without compilling from source, as far as I have seen.

**Comment by littlesnitch** [comment]
So this is closed now.

**Comment by littlesnitch** [comment]
And sorry, git was
git version 1.7.1

**Comment by driskell** [comment]
Ah my apologies. Did you run `export GO15VENDOREXPERIMENT=1` before `go get`?
It shouldn't need to download the dependencies if you use that as they are bundled in the repository.

**Comment by littlesnitch** [comment]
Ok, cool. This worked with
GO15VENDOREXPERIMENT=1 go get -v github.com/driskell/log-courier
