### ISSUE TITLE
backwards-compatible mode?

### ISSUE THREAD

**Issue by tedder** [driskell/log-courier#32]
Hi, after reviewing the configuration and [integration](https://github.com/driskell/log-courier/blob/develop/docs/LogstashIntegration.md) docs, it appears it is necessary to install both log-courier (forwarder) and log-courier (server). Is that correct?

To put it another way, does this mean there's no backwards-compatible mode using the lumberjack input?

It appears the answer is "no", based on #16.

**Comment by matthughes** [comment]
@driskell So is the logcourier server plugin a drop-in replacement for the lumberjack plugin?  I have existing clients using lsf and would love to take advantage of the improvements logcourier has.

**Comment by tedder** [comment]
@matthughes depends what you mean by "drop-in". It can't read lumberjack inputs, nor can lumberjack read logcourier inputs. You can run them side-by-side (on different ports) or you can remove lumberjack and put logcourier on the same port. I chose the former option.

**Comment by matthughes** [comment]
Ok thanks.  I was hoping to replace lumberjack on the server as I migrate my clients, but looks like I'll have to do that in tandem.

**Comment by tedder** [comment]
Yeah, that's why I brought up both. I have Ansible bits if you want 'em.

**Comment by driskell** [comment]
@matthughes Yes @tedder is correct the plugins are incompatible.

Main reason is the timeout fix. With log courier plugin Logstash sends periodic updates to Log Courier to tell it which events it has completed. This communication serves two purposes: prevent timeouts, and prevent full duplication on subsequent timeout or general failure (it knows how many events were completed)

This is possible using the lumberjack protocol, however the forwarder never implemented the full protocol, it treats any and all return messages as a full acknowledgement of all events.

So rather than cause issues and further problems I created a new plugin and also a new protocol. It opened up ability to extend and improve it further too. It's no longer key value too and so the fields in the Log Courier config file can be arrays and dicts too (main use is multiple tags as an array - something forwarder cannot do)

Jason

**Comment by matthughes** [comment]
> Main reason is the timeout fix. With log courier plugin Logstash sends periodic updates to Log Courier to tell it which events it has completed. This communication serves two purposes: prevent timeouts, and prevent full duplication on subsequent timeout or general failure (it knows how many events were completed)

Could you elaborate the communication paths described here?  Specifically the "periodic updates...to tell it which events it has completed." Does that preclude using a stateless load balancer?  If you had three nodes running Logstash/Logcourier plugin, what happens if the lc client points to different ones each time it sends logs?   Where is the state for "which events it has completed" stored?

**Comment by driskell** [comment]
@matthughes
> Specifically the "periodic updates...to tell it which events it has completed." Does that preclude using a stateless load balancer? If you had three nodes running Logstash/Logcourier plugin, what happens if the lc client points to different ones each time it sends logs?

A load balancer is fine but it must maintain TCP state. That is, once connection is established the remote server must remain the same. Load balancers that work with TCP already do this and only balance on connection establish. They'd need to understand the courier protocol to balance within a connection.

> Where is the state for "which events it has completed" stored?

In the .log-courier file in the working directory, much like forwarder itself does.

Jason

**Comment by matthughes** [comment]
Right, but if the connection to the server got interrupted and the client tried to reconnect, it wouldn't be a problem if it connected to a different node in the LB pool.  Is that correct?

**Comment by driskell** [comment]
Yes correct. When it reconnects it'll resume where it left off with the previous server.
