### ISSUE TITLE
provide rsync access to mirror

### ISSUE THREAD

**Issue by bastelfreak** [driskell/log-courier#329]
Hi, first of all, thanks for the great software!

I'm using log-courier on a few thousand nodes but they do not have direct internet access. Would it be possible for you to create a mirror that also serves the content via rsync and not only http? This would allow us way easier mirroring.

**Comment by driskell** [comment]
Hello!

Unfortunately I don't really have the resource to host something like that and maintain it. If the content you need is the source then I can only thing GitHub API. For RPMs maybe `wget` might be able to recursively pull files because I think you can browse the HTTP area where they sit. For `deb` it might be the same. Hope that helps.
