### ISSUE TITLE
default logcourier config location?

### ISSUE THREAD

**Issue by tedder** [driskell/log-courier#358]
I'm finally upgrading to logcourier2. Neither 'configuration' nor 'commandlinearguments' indicate there is a default config location for starting logcourier.  In the 1.x era I used `supervisor`, but now that it's a legit service.. how should I handle this? I suppose I can put it in the `/etc/default/log-courier` file, but I might be overlooking a default location.

**Comment by driskell** [comment]
Sorry for the silence.

The default is looking up in the current directory. However, there's a way to compile which sets a default directory instead of the current directory. For my package builds I set it to `/etc/log-courier/log-courier.yml` IIRC. This I would recommend.

The `/etc/default` or `/etc/sysconfig` folders are generally for service startup configuration as opposed to actual runtime configuration, and are usually shell scripts. Those won't be read by the log-courier binary at all. If you use my `contrib` folder init scripts then they do reference this and you can set the `USER` there.
